# Application
server:
  address: ${SERVER_ADDRESS}
  servlet.context-path: /

# Spring
spring:
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

# Flyway
  flyway:
    enabled: true
    locations: classpath:/db/migration

# Custom environment variables
custom:
  postgres:
    conn: ${POSTGRES_CONN}
    jdbc_url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    database: ${POSTGRES_DATABASE}



