services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: gradle_example_app
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/avito
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  backend:

